import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Params, useQuery, useSubscribe } from '@/hooks/'

const inter = Inter({ subsets: ['latin'] })

const params: Params = {
  query: {
    sql: "SELECT * FROM mz_internal.mz_source_statuses",
    key: "replica_id",
  },
  config: {
    auth: {
      user: "<USER>",
      password: "<PASSWORD>"
    },
    host: "<HOST>"
  }
};

export default function Home() {
  const { data: subscribeData } = useSubscribe(params);
  const { data: queryData } = useQuery(params);

  console.log(subscribeData, queryData);

  return (
    <>
      <Head>
        <title>Create Materialize App</title>
        <meta name="description" content="Generated by create materialize app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://materialize.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src="/materialize-logo.svg"
                alt="Materialize Logo"
                className={styles.vercelLogo}
                width={200}
                height={60}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <h1 className={inter.className}>Boilerplate for Materialize Apps</h1>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Materialize.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
